#!/bin/bash

# Desarrollar un software que le solicite al usuario el ingreso de 2 números 
# y le muestre al usuario el resultado de la división de esos números.

read -p "Número: " number1
read -p "Número: " number2

result=$((number1 + number2))

echo "La división es: $result"

exit 0
