#!/bin/bash

# Desarrollar un algoritmo que muestre la tabla de multiplicar de un número dado.

read -p "Número: " number

clear 

echo "Tabla del: $number"
echo "===== ==="
echo

for ((i = 1; i < 10; i++)) {
	echo "$number X $i:" $((number * i))
}

echo

exit 0
