#!/bin/bash

# Desarrollar un algoritmo que imprima la suma de todos los números que van del 1 al 100.

summation=0

for ((i = 1; i <= 100; i++)) {
	summation=$((summation + i))
}

echo "Sumatoria 1 al 100: $summation"

exit 0
