#!/bin/bash

# Desarrollar un algoritmo que rellene un vector con los números impares comprendidos entre 1 y 100
# y los muestre en pantalla en orden ascendente. 

position=0

for ((i = 1; i <= 100; i++)) {
	if ((i % 2 != 0)) 
	then
		vector[$position]=$i
		position=$((position + 1))
	fi
}

for ((i = 0; i < position; i++)) {
	echo ${vector[i]}
}

exit 0
