#!/bin/bash

# Dados tres números enteros distintos escriba un algoritmo para escribirlos
# ordenadamente de menor a mayor. 

read -p "Número: " number1
max=$number1
min=$number1

read -p "Número: " number2
if ((number2 > max))
then
	max=$number2
else
	min=$number2
fi

read -p "Número: " number3
if ((number3 > max))
then
	max=$number3
elif ((number3 < min))
then
	min=$number3
fi

if ((number1 != max && number1 != min))
then
	mid=$number1
elif ((number2 != max && number2 != min))
then
	mid=$number2
else
	mid=$number3
fi

echo "$min $mid $max"

exit 0
