#!/bin/bash

# Escriba un algoritmo para mostrar por pantalla el nombre del día de acuerdo 
# a un número (del 1 al 7) que se pase como entrada.

read -p "Número de día: " dayNumber

if ((dayNumber == 1))
then
	echo "Domingo"
elif ((dayNumber == 2))
then
	echo "Lunes"
elif ((dayNumber == 3))
then
	echo "Martes"
elif ((dayNumber == 4))
then
	echo "Miércoles"
elif ((dayNumber == 5))
	echo "Jueves"
elif ((dayNumber == 6))
then
	echo "Viernes"
elif ((dayNumber == 7))
then
	echo "Sábado"
else
	echo "ERROR"
	exit 1
fi

exit 0
