#!/bin/bash

# Desarrollar un programa que solicite el ingreso de cuatro números. 
# Determinar si el primero y el segundo son iguales, o el tercero y 
# el cuarto son iguales.

read -p "Número" number1
read -p "Número" number2
read -p "Número" number3
read -p "Número" number4

if ((number1 == number2 || number3 == number4))
then
	echo "Hay igualdad 1-2 o 3-4"
fi

exit 0
